apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-java-web-app
  namespace: tap-dev
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tanzu-java-web-app
    apps.tanzu.vmware.com/has-tests: true
    apps.tanzu.vmware.com/sonar-scan: true
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  - name: gitops_repository
    value: ssh://git@github.com/sreeramsunkara/tap-delivery
  source:
    git:
      url: https://github.com/sreeramsunkara/tanzu-java-web-app
      ref:
        branch: main
  gitops_repository: ssh://git@github.com/sreeramsunkara/tap-deliver.git
